openai:
  - versions:
      include: '>=4.19.0 <6'
      mode: max-5
    commands: npm test
  # It is a little bit hacky to get TAV to consider prereleases.
  # Once there are non-prerelease 5.x releases we can drop this block.
  - versions:
      include: '>=5.0.0-alpha.0 <5.0.0-rc.99'
      mode: max-2
    commands: npm test
