name: test

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.asciidoc'
    - 'docs/**'
    - 'examples/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.asciidoc'
    - 'docs/**'
    - 'examples/**'

# Cancel jobs running for old commits on a PR. Allow concurrent runs on 'main'.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  test-vers:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '22'
          - '22.0'
          - '20'
          - '20.0'
          - '18'
          - '18.0'
          - '16'
          - '16.0'
          - '14'
          - '14.18.0'

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_HOST_AUTH_METHOD: 'trust'
          POSTGRES_USER: 'postgres'

      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: 'Y'
          MSSQL_SA_PASSWORD: 'Very(!)Secure'
        ports:
          - "1433:1433"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Update npm to a version that supports package-lock lockfileVersion=2.
      if: ${{ startsWith(matrix.node, '14') }}
      run: npm install -g npm@9 # npm@9 supports node >=14.17.0
    - run: npm run ci-all
    - run: npm test

  # TODO: test-windows eventually
